tables:
  # An example of additional Piccolo Admin configuration
  # Actor:
  #   visible_columns:
  #     - actor_id
  #     - first_name
  #   visible_filters:
  #     - actor_id
  #     - first_name
  #   menu_group: Movies
  #   link_column: first_name
  # Address:
  #   visible_columns:
  #     - address_id
  #     - address
  #     - city_id
  #   visible_filters:
  #     - address_id
  #     - address
  #     - city_id
  #   menu_group: Location
  #   rich_text_columns: address # it only works in the Text type column
  # City:
  #   visible_columns:
  #     - city_id
  #     - city
  #   visible_filters:
  #     - city_id
  #     - city
  #   menu_group: Location
  # Country:
  #   visible_columns:
  #     - country_id
  #     - country
  #   visible_filters:
  #     - country_id
  #     - country

sidebar_links:
  # Piccolo Admin: https://piccolo-admin.readthedocs.io/en/latest/index.html
  # Piccolo ORM: https://piccolo-orm.readthedocs.io/en/latest/index.html